### ISSUE TITLE
Create a generic visualization for errors.

### ISSUE THREAD

**Issue by eupedrosa** [lardemua/atom#103]

**Comment by miguelriemoliveira** [comment]
@afonsocastro can help if needed. He already did the results_visualization.py

**Comment by afonsocastro** [comment]
yes, I can help!

**Comment by eupedrosa** [comment]
@miguelriemoliveira, was this kinda of error reporting that you were talking about?

![etb](https://user-images.githubusercontent.com/6196901/73092064-bc83d780-3ed3-11ea-999c-72afcc1780b5.png)

**Comment by miguelriemoliveira** [comment]
Yes! It looks great! Congrats!

BTW, it is funny how your errors seem to resemble the structure of the chessboard ... this also occurs in (1), look at Fig 10 B. 
This means we are on the right track.

Some nitpicking though (otherwise you'll think its perfect): put the legend always on the same position for consistency, and the characters should be larger.

nitpicking number 2: if we could draw the graph in an intermediate stage after doing a manual first guess that would look good.

(1) Calibrating a multi-arm multi-sensor robot: A Bundle Adjustment Approach

**Comment by miguelriemoliveira** [comment]
Hi @eupedrosa , this looks nice, but I did not get it ... is it generic?

**Comment by eupedrosa** [comment]
Not yet... but it is a start!!

**Comment by miguelriemoliveira** [comment]
Its a great start!
