### ISSUE TITLE
Integration with Rviz Panel - Collect Data - Save collection

### ISSUE THREAD

**Issue by MiguelDRPina** [lardemua/atom#287]
Title says it. We have to be able to save the collections made.

**Comment by miguelriemoliveira** [comment]
Hi @MiguelDRPina ,

the save collection integration with the rviz panel is as simple as the **reset all sensors** functionality for the set_initial_estimate.

Because we have a menu before, you just have to use the currently existing menu once and see the message that rviz sends on the topic "feedback". 

Then your panel code just has to mimic this message when the corresponding button is pressed.

Let me know if you need help here.
