### ISSUE TITLE
Integration with Rviz Panel - Create rviz pannel to read write the calibration config file variables

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#292]

**Comment by miguelriemoliveira** [comment]
Hi @MiguelDRPina ,

any progress? Do you want to meet tonight?

**Comment by MiguelDRPina** [comment]
Hello, @miguelriemoliveira ,
Yes, I have been making some progress. Forgot to commit, sorry. As soon as I get home I'll do that.

Maybe not tonight, I am having a little trouble reading the calibration_pattern/border_size and calibration_pattern/dimension parameters because they are a dictionary, but I want to give it another try later today. If today I am not able to do it, we can arrange an hour any other day that works for both of us.

**Comment by miguelriemoliveira** [comment]
Hi @MiguelDRPina ,

agreed. Lets try to arrange during the weekend. Please keep updating the github.

**Comment by MiguelDRPina** [comment]
Hello @miguelriemoliveira,
I have already updated the github. I am still missing the part for reading the /calibration_pattern/border_size and /calibration_pattern/dimension parameters from the config file because they are dictionaries. From what I understood, I am supposed to use XmlRpc to do it, but haven't quite figured out how.

**Comment by miguelriemoliveira** [comment]
Yes, I can help you with it. I think I did it before. Before that, did you try this?

https://wiki.ros.org/roscpp/Overview/Parameter%20Server#Retrieving_Lists

**Comment by MiguelDRPina** [comment]
Yes, I have also tried to use getParam and store it in a std::map and the code compiles with no error. But then I don't know how to see the content of the map variable I created.

**Comment by miguelriemoliveira** [comment]
Hi Miguel,

https://www.google.com/search?q=animatedcharts&oq=animatedcharts&aqs=chrome..69i57j0i13l4.7316j0j9&client=tablet-android-samsung-nf-rev1&sourceid=chrome-mobile&ie=UTF-8#

This helps?

**Comment by MiguelDRPina** [comment]
AnimatedCharts? Is that the right link?

**Comment by MiguelDRPina** [comment]
I was able to read the first value, just by doing something like this:

`std::map<std::string, double> dict_param;

  nh.getParam("/calibration_pattern/border_size", dict_param);

  ROS_INFO_STREAM(dict_param.begin()->first);

  ROS_INFO_STREAM(dict_param.begin()->second);`

The 'first' returns the key and the 'second' returns its value. In this case, it is returning 'x' for the first, and 0.04 for the second.
Now I just have to try to iterate this to get the remaining of the keys and their respective values.

**Comment by miguelriemoliveira** [comment]
This one

https://thispointer.com/stdmap-tutorial-part-1-usage-detail-with-examples/

Sorry

**Comment by miguelriemoliveira** [comment]
Thats it. The example i sent iterates all dict keys.

**Comment by MiguelDRPina** [comment]
You're right, that example works. Thank you!

**Comment by miguelriemoliveira** [comment]
I don't think we will be doing this. We could later on develop something similar to moveit assistant but not for now.
