### ISSUE TITLE
Disparities in calibration results

### ISSUE THREAD

**Issue by danifpdra** [lardemua/atom#325]
Hi @miguelriemoliveira ,

I just tested with mmtbot... you can still see the ghost but not like larcc

![image](https://user-images.githubusercontent.com/47574905/140985753-12165a66-2753-4452-90ab-ca79fb2b8816.png)

**Comment by miguelriemoliveira** [comment]
Hi @danifpdra , what was the command to run this mmtbot test?

**Comment by miguelriemoliveira** [comment]
Hi @danifpdra ,

I cannot run the mmtbot test. I think our bags and datasets are deprecated because of the changes in the description and gazebo packages. Which are you using? Perhaps you can add them to the readme.

Also, let me know the command.

I think that we should clarify why this is also occurring in mmtbot (even if to a lesser extent)

**Comment by danifpdra** [comment]
The bag is here: https://uapt33090-my.sharepoint.com/:u:/g/personal/danielarato_ua_pt/EQyry8hklGpPn_JPyUTYOy4BMAIDgD43Tosi6w7TafTiJQ?e=8FopnX

The dataset is here: https://uapt33090-my.sharepoint.com/:u:/g/personal/danielarato_ua_pt/EX8xycbjBS9PjEMsbr13bJoBZJcNCRVttXd7xijCj30RHg?e=Jw6VMz

I will add this to the readme also.


I used 

`rosrun atom_calibration calibrate -uic -json $ATOM_DATASETS/mmtbot/test_mmtbot/data_collected.json -nig 0.05 0.05 -rv -ipg -v -phased -si`

**Comment by miguelriemoliveira** [comment]
Migrating to #327. This seems to be the problem...

**Comment by miguelriemoliveira** [comment]
This was solved, I think. Closing.
