### ISSUE TITLE
Chessboard being poorly detected in RGB with lower resolution 

### ISSUE THREAD

**Issue by danifpdra** [lardemua/atom#341]

**Comment by miguelriemoliveira** [comment]
Give me more information please. What system is this? How far does the pattern have to be? How to I run the debug detector? Can you add a picture?

**Comment by danifpdra** [comment]
Run system:

`roslaunch mmtbot_gazebo mmtbot.launch sim:=true gui:=true moveit:=true`

Run debug:

`python view_pattern.py -t charuco -x 11 -y 8 -L 0.06 -l 0.045 /world_camera/rgb/image_raw`

The pattern has to be pretty close to be detected:
![image](https://user-images.githubusercontent.com/47574905/146959392-0198af9e-363f-49a0-8821-7d138bb51cc8.png)
![image](https://user-images.githubusercontent.com/47574905/146959536-c5cd7cf4-4c7f-43a9-8725-587d74ccabcd.png)

**Comment by miguelriemoliveira** [comment]
Thanks @Daniela Rato ***@***.***> ,

I will try it out and get back to you.


*  Miguel Riem de Oliveira                                             *
Diretor de curso Mestrado Eng. Automação Industrial
email:    ***@***.***    |    ***@***.***
zoom: https://videoconf-colibri.zoom.us/j/7155402102
office: 22.2.18                 |    ext: 23887
Dep. de Engenharia Mecânica, Universidade de Aveiro
*Campus Universitário de Santiago, 3810-193  Portugal*

**Comment by miguelriemoliveira** [comment]
Hi @danifpdra ,

I just tried it out. It is also a problem with the light. I just added a couple of lights and the pattern is detected much further away.

![image](https://user-images.githubusercontent.com/11350998/147065741-8b2aa85d-f1b0-4646-918e-cfa4233fe1d5.png)

In any case I will look into the detector's configuration.

**Comment by miguelriemoliveira** [comment]
Hi @danifpdra ,

I looked into the parameters. They are commented in the detector code here:

https://github.com/lardemua/atom/blob/d5632dd64dfff0735f141add0b9a716b7884b2bb/atom_calibration/src/atom_calibration/collect/patterns.py#L95-L110

You can try to adjust them but do not commit those changes because that code is used by all atom.
I tried but it does not really change anything much. In any case, turning off the equalization of the histogram certainly helps:

https://github.com/lardemua/atom/blob/d5632dd64dfff0735f141add0b9a716b7884b2bb/atom_calibration/scripts/deprecated/view_pattern.py#L37

Apart from that, adding lights in gazebo was what worked best.

Let me know if you can detect the patter further away with these changes.

**Comment by danifpdra** [comment]
Hi @miguelriemoliveira,

Thanks. I will try it out and let you know.

**Comment by miguelriemoliveira** [comment]
Ok, if you need more help let me know.

**Comment by danifpdra** [comment]
Hi @miguelriemoliveira,

For what I can see you didn't push the world with the new lights

**Comment by miguelriemoliveira** [comment]
Strange. In any case please add new lights from your side as needed. I can't do it now.
