### ISSUE TITLE
Problems with depth labelling

### ISSUE THREAD

**Issue by danifpdra** [lardemua/atom#368]
Hi @miguelriemoliveira,

There are some problems with the depth labelling...

![image](https://user-images.githubusercontent.com/47574905/159329761-ad753e3f-e4fc-47c6-9f00-df990cdd4a34.png)

Do you think there is some way to fix it or to add the depth modality to the dataset playback so we can fix it afterwards? (@DanielCoelho112)

**Comment by miguelriemoliveira** [comment]
Hi @danifpdra ,

yes, we were counting on this. However, I think that we should label the image, rather than the point cloud in this case. As such, this is more similar to the work of @manuelgitgomes .

The problem is this was not finished, right @manuelgitgomes . It was not functional yet, was it?

Since we are pressed to have some results fast I can try to work on this on wednesday and thursday. 

@danifpdra , can you move on to something else and wait for Thursday?

**Comment by manuelgitgomes** [comment]
Hello to both @danifpdra and @miguelriemoliveira!
As shown on issue #367, the functionality does not exist yet.

**Comment by miguelriemoliveira** [comment]
This is solved I think.
