### ISSUE TITLE
inconsistencies in lidar 3d labelling in real data

### ISSUE THREAD

**Issue by danifpdra** [lardemua/atom#377]
![image](https://user-images.githubusercontent.com/47574905/160670807-d13a720a-65a8-44f7-82a9-bb0820184d93.png)
![image](https://user-images.githubusercontent.com/47574905/160670891-1ed20f2a-d2e1-48f0-a977-b1b758076e1d.png)
![image](https://user-images.githubusercontent.com/47574905/160671062-bd08723d-41c0-479f-8d06-88816955c762.png)
![image](https://user-images.githubusercontent.com/47574905/160671138-efa3a1ab-683d-4f3a-b1b4-c275908e9da4.png)
![image](https://user-images.githubusercontent.com/47574905/160671300-8dff134d-cb6b-4f91-b0f3-3f01aba3d944.png)
![image](https://user-images.githubusercontent.com/47574905/160671397-53ac75d3-9a5a-448a-ab4c-8032ee0a681b.png)

**Comment by miguelriemoliveira** [comment]
Hi @danifpdra ,

I wonder if this **threshold** must be tuned.

https://github.com/lardemua/atom/blob/f3ee867bd7806ec72d7654276d0b17d86bd2001f/atom_calibration/src/atom_calibration/collect/label_messages.py#L30

Can you change it to a larger value and see if it works better?

The function call is here:

https://github.com/lardemua/atom/blob/f3ee867bd7806ec72d7654276d0b17d86bd2001f/atom_calibration/src/atom_calibration/collect/interactive_data_labeler.py#L443

and the definition of the threshold here 

https://github.com/lardemua/atom/blob/f3ee867bd7806ec72d7654276d0b17d86bd2001f/atom_calibration/src/atom_calibration/collect/interactive_data_labeler.py#L203

For example, set the value to 2.0 instead of 0.8 , does it work better?

**Comment by miguelriemoliveira** [comment]
Hi @danifpdra ,

I think I know what happens here. In order to figure out the selection of some points rviz uses an image to compute the selection. 
If the resolution is low some objects may shadow others. From my experience, if you want to select all points in the pattern get close to it starting to create the selection rectangle.

**Comment by danifpdra** [comment]
This problem was related to the automatic labelling, not the manual labelling.

**Comment by miguelriemoliveira** [comment]
Right, sorry. Perhaps you can try the ransac suggestion above? Or give me the instructions on how to replicate...

**Comment by danifpdra** [comment]
Yes, I can try it, maybe after the paper? I've manage to correct the problem with the dataset_playback for now, so this wasn't/isn't really a priority

**Comment by miguelriemoliveira** [comment]
Agree.
