### ISSUE TITLE
Depth labelling is not discarding edges in the image limits?

### ISSUE THREAD

**Issue by danifpdra** [lardemua/atom#380]
@miguelriemoliveira , I was looking at the depth labelling and it seems we are not discarding the depth edges that coincide with the images' limits. Or is it just a visualization "problem"?

![image](https://user-images.githubusercontent.com/47574905/161270043-49123809-209c-4ddb-a3e1-b43c4264f285.png)

**Comment by danifpdra** [comment]
I was checking here where the idx_limits are set and I don't see any filtering. Am I missing it?

https://github.com/lardemua/atom/blob/2d2aeeb2a90a9881124d11eb289287470c82a293/atom_calibration/src/atom_calibration/collect/label_messages.py#L530-L575

**Comment by miguelriemoliveira** [comment]
Right, I don't see any. It should be implemented.

Another option which I am not sure its better (we should discuss) is to set the detected to false if we see that the pattern is near the borders.

I say this because I am not sure if the objective function is not misled by the fact that we have borders missing.

In any case, the objective function is surely misled if we have incorrect borders dues to the image limits. This must be addressed.

**Comment by danifpdra** [comment]
We have partial detections in the LiDAR and seems to handle well those collections... Isn't the philosophy the same?

**Comment by miguelriemoliveira** [comment]
Do we? I though we never had partial detections in the lidars ... Am I missing something? Can you show an example?

**Comment by danifpdra** [comment]
For example here there is a corner missing
![image](https://user-images.githubusercontent.com/47574905/161278694-d3155fda-478a-47d9-a9ba-3397cbd0bb08.png)

**Comment by miguelriemoliveira** [comment]
You are right. 

Now thinking better about this, all we do is pick up these points and see how far they are from any border in the ground truth of the pattern. 

If this is definitely the way we do it (I mean, it cannot be the other way around), then the objective function should not be misled if we just delete some boundaries.

That's exactly what happens here, the top and the bottom boundaries are not annotated, but that's ok because it will use only the left and right annotations to compute the longitudinal error.

**Comment by danifpdra** [comment]
So the conclusion is that we should implement the filtering of those edge points?

**Comment by miguelriemoliveira** [comment]
Yes. We dont need to make the entire label false, just remove those points
near the image borders.

**Comment by danifpdra** [comment]
Ok. Should I implement or you rather do it yourself?

**Comment by miguelriemoliveira** [comment]
Please do it. I am working on the rviz plugin ...

**Comment by danifpdra** [comment]
https://we.tl/t-ugvspPNkEY

**Comment by danifpdra** [comment]
Hi @miguelriemoliveira ,

![image](https://user-images.githubusercontent.com/47574905/161388937-d75239fa-2023-4cb9-a2d8-9a1c87bd6022.png)

Working
