### ISSUE TITLE
Weird labels on RGB images

### ISSUE THREAD

**Issue by danifpdra** [lardemua/atom#383]
Hi @miguelriemoliveira ,

Is this normal during calibration?

![image](https://user-images.githubusercontent.com/47574905/161724813-427636ce-45da-416c-a5fa-0ce1a776d326.png)

**Comment by miguelriemoliveira** [comment]
Hi @danifpdra ,

I think so, because:

   - squares are the ground truth
   - dots are the current projections of the pattern corners to the image, using the currently estimated transformations (and intrinsics)
   - crosses are the projection obtained using the initial values of the transformations

So in the end what we want are the dots inside the squares. That's what's happening, so it seems fine.

Because of the crosses, we can also say your initial guess is really far from the optimal solution.

Makes sense?
