### ISSUE TITLE
Evaluation scripts retrieving the intrinsics of test dataset

### ISSUE THREAD

**Issue by manuelgitgomes** [lardemua/atom#496]
In evaluation. the intrinsic parameters used are the ones from the test dataset and not the ones optimized from the train dataset.
Should this be like this?
https://github.com/lardemua/atom/blob/60f89351f7d518f107c35036eb29a45551621681/atom_evaluation/scripts/rgb_to_rgb_evaluation#L208-L211

**Comment by miguelriemoliveira** [comment]
Hi @manuelgitgomes ,

actually they are copied from the train to the test dataset some lines above:

https://github.com/lardemua/atom/blob/60f89351f7d518f107c35036eb29a45551621681/atom_evaluation/scripts/rgb_to_rgb_evaluation#L188-L194

But I don't like this way of doing it, because its confusing.

We should have a train dataset, a test dataset, and a mixed dataset.
This way its more explicit.

I did a function to produce the mixed dataset from the train and test datasets.
It is defined here:

https://github.com/lardemua/atom/blob/671e301310a0543ab91a99ba7c7ef9a4dbd33551/atom_core/src/atom_core/dataset_io.py#L668-L706

and used here

https://github.com/lardemua/atom/blob/671e301310a0543ab91a99ba7c7ef9a4dbd33551/atom_evaluation/scripts/depth_to_rgb_evaluation#L64-L73

and here

https://github.com/lardemua/atom/blob/671e301310a0543ab91a99ba7c7ef9a4dbd33551/atom_evaluation/scripts/lidar_to_rgb_evaluation#L91-L100

Once I have time I will put all evaluation scripts using this method (#497).

If you can you should also use this method.

**Comment by manuelgitgomes** [comment]
Ok, thank you!

**Comment by manuelgitgomes** [comment]
In the lidar_to_rgb_evaluation, this creates false results, as in here:
https://github.com/lardemua/atom/blob/6ccf25d521dae877c98d591ace3ebc128bf50a7c/atom_evaluation/scripts/lidar_to_rgb_evaluation#L59-L60

The test dataset intrinsic parameters are used and they are not copied from the train one. This can massively influence results.
This was already implemented on my thesis, but here is an example to see the difference.

With test_dataset intrinsics:

```bash
+--------------+-----------+-------------+-------------+
| Collection # | RMS (pix) | X err (pix) | Y err (pix) |
+--------------+-----------+-------------+-------------+
|     000      |  18.1944  |   16.7315   |    1.8319   |
|     001      |  18.8009  |   18.2321   |    3.9841   |
|     002      |  17.4234  |   15.7554   |    1.1450   |
|     003      |  16.6294  |   15.0630   |    1.7186   |
|     004      |  18.0244  |   17.7525   |    2.3962   |
|     005      |  20.0553  |   18.8434   |    1.6509   |
|     006      |  19.4746  |   17.8448   |    3.6759   |
|     009      |  22.7332  |   20.5353   |    6.3123   |
|     010      |  20.1684  |   19.0858   |    4.4311   |
|     011      |  20.3024  |   19.3066   |    1.8838   |
|     012      |  22.0014  |   21.6773   |    2.6799   |
|     014      |  16.8652  |   14.4245   |    1.8287   |
|     015      |  16.8259  |   14.5841   |    1.5382   |
|     016      |  16.4739  |   15.3625   |    1.5854   |
|     017      |  17.9937  |   16.8902   |    1.5757   |
|     018      |  18.7297  |   17.2471   |    2.8343   |
|   Averages   |  18.7935  |   17.4585   |    2.5670   |
+--------------+-----------+-------------+-------------+
```

With train_dataset/mixed_dataset intrinsics:

```bash
+--------------+-----------+-------------+-------------+
| Collection # | RMS (pix) | X err (pix) | Y err (pix) |
+--------------+-----------+-------------+-------------+
|     000      |   2.5749  |    2.1152   |    0.4102   |
|     001      |   1.8872  |    1.1928   |    0.6328   |
|     002      |   2.6904  |    1.9781   |    0.5289   |
|     003      |   1.7211  |    1.2775   |    0.2802   |
|     004      |   2.3270  |    1.8913   |    0.4353   |
|     005      |   3.8848  |    2.6145   |    0.6849   |
|     006      |   3.2939  |    2.3595   |    0.4635   |
|     009      |   3.3451  |    2.8958   |    0.4040   |
|     010      |   2.0014  |    1.4697   |    0.3808   |
|     011      |   3.1420  |    2.6899   |    0.2473   |
|     012      |   2.9675  |    2.5082   |    0.1762   |
|     014      |   2.5408  |    1.7449   |    0.7751   |
|     015      |   1.6158  |    1.2102   |    0.4231   |
|     016      |   2.6428  |    2.3458   |    0.3759   |
|     017      |   1.8528  |    1.2071   |    0.5871   |
|     018      |   3.2339  |    2.3781   |    1.0322   |
|   Averages   |   2.6076  |    1.9924   |    0.4898   |
+--------------+-----------+-------------+-------------+

```

**Comment by miguelriemoliveira** [comment]
Not sure what you mean. I will call you later.

**Comment by manuelgitgomes** [comment]
Remove train_dataset and test_dataset after mixed is created
