### ISSUE TITLE
comparison with robot_calibration?

### ISSUE THREAD

**Issue by v4hn** [lardemua/atom#532]
Someone just pointed me at this framework after I spent quite a bit of time (successfully!) setting up https://github.com/mikeferguson/robot_calibration for our system recently. I am happy with we have there right now, but I do wonder what kind of advantages it could bring along to switch to ATOM.

You do list various papers and compare to quite a few baselines in your publications, but I did not find a comparison to @mikeferguson's work and was somewhat wondering why.

**Comment by mikeferguson** [comment]
I'm going to guess that's at least partially because I don't have any academic papers published on robot_calibration (we did have a ROSCON talk, but never actually got the academic paper accepted since it wasn't a big enough "theory" improvement over [Calibrating a Multi-arm Multi-sensor Robot](https://www.semanticscholar.org/paper/Calibrating-a-Multi-arm-Multi-sensor-Robot%3A-A-Pradeep-Konolige/792b676203325c434d56bc9765044ac5e6833a11).

**Comment by eupedrosa** [comment]
Hi @v4hn

> I am happy with we have there right now, ...

If [robot_calibration](https://github.com/mikeferguson/robot_calibration) works great for you may not need to change it.

But you can take a look at https://lardemua.github.io/atom_documentation and see if you find the information useful.

>... but I do wonder what kind of advantages it could bring along to switch to ATOM.
>
> You do list various papers and compare to quite a few baselines in your publications, but I did not find a comparison to @mikeferguson's work and was somewhat wondering why.

I guess that @mikeferguson may be partially correct. The lack of an academic paper may have been one of the reasons why is was not mentioned (maybe deposit the paper at https://arxiv.org/ ??). But it is hardly the only reason.

**Comment by miguelriemoliveira** [comment]
Hi @v4hn ,

> but I did not find a comparison to @mikeferguson's work and was somewhat wondering why.

we did not know about the software, but the paper @mikeferguson cites was actually a source of inspiration back in 2018 when we started ATOM. We actually cite this paper in our most recent publication  for sure (https://linkinghub.elsevier.com/retrieve/pii/S0957417422012234), and I think in some others as well.

I went to take a look at the [robot_calibration](https://github.com/mikeferguson/robot_calibration). It looks very interesting. If we can put it working in our problems we will surely compare against it in future publications, since we are always lacking other approaches to compare against.

In any case the main argument we use for ATOM was not that we could calibrate more accurately than other approaches, but rather that ATOM was general enough to handle a large number of cases other other approaches would not, while maintaining a similar level of accuracy. 
Not sure if this holds for  [robot_calibration](https://github.com/mikeferguson/robot_calibration) though.

Since I do not know robot_calibration I cannot tell you the advantages / disadvantages of ATOM in comparison to it. 
ATOM offers a calibration framework for calibrating robotic systems with multiple sensors, multiple modalities (rgb, deph, lidar3d). It also breaks down the calibration procedure into several components (data collection, calibration, evaluation, etc) and has tools to address each of those.
Like @eupedrosa suggested, if you read through the documentation hopefully you will have a clear idea of what ATOM does.

**Comment by miguelriemoliveira** [comment]
> we did have a ROSCON talk, but never actually got the academic paper accepted since it wasn't a big enough "theory" improvement over

@mikeferguson , we also get a lot of these kind of reviews ... "it is only incremental", "no real contribution", etc. 
For example, in our last paper, one reviewer suggested that an entire section on the integration of ATOM with ROS was to be moved to appendix. According to him, the real scientific contribution was the ATOM method, not the implementation.
We ended up removing the entire section and hope to publish it in another place sometime soon, although we expect to face the same difficulties ...

BTW, I have a Ph.D. student, @manuelgitgomes , who is going to give a presentation in ROSCON about ATOM in October.
