### ISSUE TITLE
When fixed pattern used?

### ISSUE THREAD

**Issue by dimaxano** [lardemua/atom#561]
Hello!

Thank you very much for a great tool! Btw I'm using it to calibrate my ROS2 based robot (I just convert ROS2 bag to ROS1 basically), so I can provide instruction for ROS2 users, If you are interested

I have a question: what is the calibration case when `fixed` pattern param must be set to true? I guess we usually move pattern or robot around the pattern

**Comment by miguelriemoliveira** [comment]
Hi @dimaxano ,

> Thank you very much for a great tool! Btw I'm using it to calibrate my ROS2 based robot (I just convert ROS2 bag to ROS1 basically), so I can provide instruction for ROS2 users, If you are interested

Thanks for your interest. We are planning to develop a ROS2 version in the near future (#544), but that's a great idea as a solution for now. Could you provide some instructions on how you do it? I could include them here:

https://lardemua.github.io/atom_documentation/#ros1-and-ros2

> I have a question: what is the calibration case when fixed pattern param must be set to true? I guess we usually move pattern or robot around the pattern

Its funny that you ask. I was trying to find what was wrong with a calibration that was not working, and the problem was exactly setting this flag incorrectly (#555 ).

Because of that, I changed the instructions in the config.yaml to:

```
 # Defines if the pattern link is the same in all collections (i.e. fixed=true),
  # or each collection will have its own estimate of the link transformation.
  # Note: if you plan to have the pattern fixed, while the moving the rigidly attached sensors, 
  # this is equivalent to having the sensors fixed and the pattern moving, so you should use fixed=false.
  fixed: true
``` 

does it help? If not, describe to me your robotic system and how you plan to carry out the calibration.
