### ISSUE TITLE
Why pattern initial pose estimated only for one sensor?

### ISSUE THREAD

**Issue by dimaxano** [lardemua/atom#563]
I see that the initial pattern pose estimate is done only for the first sensor in the collection ([link](https://github.com/lardemua/atom/blob/0fc14cd683236faf8cf8389f77a0e4e77585a940/atom_calibration/src/atom_calibration/calibration/patterns_config.py#L238))

What is the reason for that?

My setup:
I have two RGB cameras on the mobile base. I see during calibration that for one of the cameras (let's say the left one), the initial guess is a bit far from the correct one. And that is because (_my guess_) the initial guess calculated not via pattern pose estimation on the left camera (via solvePnP), but via transformations chain based on right camera solvePnP results and right->left camera transform (which may be not precise enough).
You can see the left camera at the bottom and the right one at the top

![image](https://user-images.githubusercontent.com/14369906/233624931-54dfc667-e743-40f5-be90-cff87662419b.png)

**Comment by miguelriemoliveira** [comment]
Hi @dimaxano ,

> I see that the initial pattern pose estimate is done only for the first sensor in the collection

The reason is that we can only have one set of values for the initial parameters. If we used multiple sensors we would have multiple first guesses and  have come up with a way to select which set of values we would use as the real initial guess.

Since we just need some initial values that are more or less plausible we found that it suffices to use the solvePnP for one camera to generate the first guess.

You can also read section 3.3 [here](https://www.mdpi.com/1424-8220/23/2/936)
