### ISSUE TITLE
Why is the evaluation table style for the lidar_to_depth_evaluation is different from all of the other evaluation table in every other sensor pair?

### ISSUE THREAD

**Issue by danifpdra** [lardemua/atom#622]
Normal tables:

![image](https://github.com/lardemua/atom/assets/47574905/6add768c-ea30-4aa3-8b87-fd1f280ef93d)

Lidar to depth table:

![image](https://github.com/lardemua/atom/assets/47574905/977c4844-1d84-47ce-bfe8-bf02a56083ea)

I am asking because this table is much bigger and it's much harder to fit in the screen

**Comment by miguelriemoliveira** [comment]
Hum, evaluations are now more on @manuelgitgomes 's side.

Can you help @manuelgitgomes ?

**Comment by manuelgitgomes** [comment]
Hello all!

This will be fixed in my PR. I can do it now so it eases the process.
In 10/15 min it will be done.

________________________________
De: Miguel Riem de Oliveira ***@***.***>
Enviado: 29 de setembro de 2023 14:56
Para: lardemua/atom ***@***.***>
Cc: Manuel Gomes ***@***.***>; Mention ***@***.***>
Assunto: Re: [lardemua/atom] Why is the evaluation table style for the lidar_to_depth_evaluation is different from all of the other evaluation table in every other sensor pair? (Issue #622)


Hum, evaluations are now more on @manuelgitgomes<https://github.com/manuelgitgomes> 's side.

Can you help @manuelgitgomes<https://github.com/manuelgitgomes> ?

**Comment by danifpdra** [comment]
Don't worry @manuelgitgomes , it's not urgent. I was just evaluating a lot of stuff and I wondered why it was the only different one. But it's just a cosmetic question

**Comment by manuelgitgomes** [comment]
Hello! This is already solved, sorry.
