### ISSUE TITLE
Create a depth label playback delete boundary points functionality

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#648]
Related to #612 

For real data e often have holes in the pattern on the depth image. This is very hard to automatically detect (or ignore) and therefore we will need a way to manually delete individual boundary points or points inside a user defined polygon  .

**Comment by miguelriemoliveira** [comment]
@danifpdra , can you continue from now ?

**Comment by danifpdra** [comment]
Hi @miguelriemoliveira , can you help? 

I am having a bit of trouble doing this because the function clickedPointsCallback is a callback and I need another callback with a global variable to commute the `depth_labeling_mode` between detect and detect and it does but the global variable doesn't seem to be changing inside the clickedPointsCallback and it keeps crashing with the same error you had

**Comment by miguelriemoliveira** [comment]
Hi @danifpdra ,

I can help, but now I do not have time. Don't waist time with that now , I will work with you tomorrow afternoon with you, ok?

**Comment by miguelriemoliveira** [comment]
Seems to be working fine.

This labeling to delete:

![image](https://github.com/lardemua/atom/assets/11350998/d4812271-cfca-4c26-a06e-8656a797d0d1)

Results in:

![image](https://github.com/lardemua/atom/assets/11350998/ae0c2105-08d1-4732-ad1c-f74536f4a8af)
