### ISSUE TITLE
Problem with LiDAR - Depth evaluation

### ISSUE THREAD

**Issue by danifpdra** [lardemua/atom#657]
Hi @miguelriemoliveira and @manuelgitgomes ,

I would like to get your opinion on this problem.

What's happening is that the LiDAR-depth pairs are giving high errors in the evaluation scripts. This is not due to bad calibration but a bug in the evaluation, or at least something we haven't thought about...

![image](https://github.com/lardemua/atom/assets/47574905/7dfb49c4-35ce-4990-af7d-73518dac3963)

In this example, we have gaps in the depth limit points, but we have LiDAR points (blue) being projected to that area. What's happening is that our evaluation script is looking for the closest point and counting it, when these LiDAR points should not be considered for evaluation... 

Here are other examples 

![image](https://github.com/lardemua/atom/assets/47574905/056c1711-4bda-45a2-9456-0cc61ef9ed6f)
![image](https://github.com/lardemua/atom/assets/47574905/fe6e904e-430c-4557-9aa8-3454bc61673f)

In my opinion, we could either discard the points that are projected for NaN zones, or we could annotate borders in the depth image like we do for RGB to evaluate.... What do you think?

**Comment by danifpdra** [comment]
In case you are wondering... These are the errors I am getting

![image](https://github.com/lardemua/atom/assets/47574905/9844d547-a484-40cf-b3e4-82e149dd1491)


For example collection 5 doesn't have a gap in the detection of the limits so the evaluation error is much lower

![image](https://github.com/lardemua/atom/assets/47574905/e5db2cb2-a967-47c5-b305-6761d8acd336)

**Comment by miguelriemoliveira** [comment]
Hi @danifpdra ,

first of all, congratulations of a very well written issue. I understood everything on the first read. You are improving a lot :+1: 

About the issue I would first say that this depth image is terrible. 

Then I would vote for the doing a manual annotation of the boundaries of the depth image. 
We can use the rgb manual annotation as a good starting point, but it does not have one functionality that we would need, which is to define only portions of the top line segment as valid. 

But I think it is easily adaptable, so if you want I can try to do it.

The other option of not evaluating lidar points which project to nan pixels in the depth image I don't like, because the location of the projection depends on the calibration ...

Lets hear what @manuelgitgomes has to say ...

**Comment by danifpdra** [comment]
I agree with you @miguelriemoliveira. Yes, the depth image is horrible but that's most of the depth real images, unless you just have a RGB-D system and focus a lot of the pattern detection in depth. 

One problem that I see is that we would need to draw the rectangle but in some parts of the pattern we don't really know where it is. And if we cut out parts of the rectangle that we don't where it is in the annotation, we would still have the same problem of LiDAR points being projected to places where there is nothing. 

Example: 

I can easily draw a rectangle to fill these limits:

![image](https://github.com/lardemua/atom/assets/47574905/21ea28d8-eeba-4a1b-8084-683ce495364b)

But in this example, I would only be guessing where the corners are, unless we have some sort of functionality that prolongs lines and allows us to find the intersection. 

![image](https://github.com/lardemua/atom/assets/47574905/b70e10b2-7c1a-4662-8c94-7e7331e9148c)

**Comment by manuelgitgomes** [comment]
Hello @danifpdra @miguelriemoliveira 

I agree with @miguelriemoliveira that a manual annotation can solve this, however, I believe this should be optional, as not all depth images need this.

Another option is to remove those images from the dataset with `-csf`

**Comment by miguelriemoliveira** [comment]
> Another option is to remove those images from the dataset with `-csf`

That would be my favorite, but I don't think @danifpdra has enough "good images " to calibrate.

**Comment by danifpdra** [comment]
> > Another option is to remove those images from the dataset with `-csf`
> 
> That would be my favorite, but I don't think @danifpdra has enough "good images " to calibrate.

What do you mean @miguelriemoliveira? This is evaluation, not calibration. I already calibrated.

**Comment by miguelriemoliveira** [comment]
> What do you mean @miguelriemoliveira? This is evaluation, not calibration. I already calibrated.

Right. I meant enough good images to evaluate.

About your comments above, I think we can do an annotation that will not have a real depth measurement.

That means we would annotate the entire top, bottom, left and right lines of the pattern (the corners can be given as an intersection, but perhaps in a later stage).

After this, since we are computing the error by projecting lidar points into the depth image, its a good thing to have all the points along the boundaries of the pattern...

**Comment by miguelriemoliveira** [comment]
Should I start?

**Comment by miguelriemoliveira** [comment]
I will work on the annotation solution. Monitoring in #660
