### ISSUE TITLE
Delete atom_calibration/meshes folder?

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#678]

**Comment by Kazadhum** [comment]
Hi @miguelriemoliveira ! Why not move the chessboard model in `atom_calibration/meshes` to the `atom_worlds/pattern/models` folder? That way I think the folder could be deleted, since `atom_worlds` already has the charuco (800x600) files.

From what I've seen so far, we rarely use chessboards when we can use charucos, but a user might prefer them for whatever reason and that way we'd have a model for them.

What do you think?

**Comment by miguelriemoliveira** [comment]
I agree. Will delete soon.

**Comment by miguelriemoliveira** [comment]
I will delete the folder since I think no one actually uses it. If we find later that it is used somewhere, then we will point to the atom_worlds model.
