### ISSUE TITLE
Create accessibility functions for joint estimations

### ISSUE THREAD

**Issue by manuelgitgomes** [lardemua/atom#724]
Need to add accessibility option for the joint estimation, such as:

- [x] Config instructions
- [x] Option for non-joint calibration
- [x] Conversion from datasets 2.x to 3.0 #723

**Comment by manuelgitgomes** [comment]
Conversion between datasets might not be needed, as joints will be handled as addtional_tfs are, so no need for a new dataset for that.

**Comment by miguelriemoliveira** [comment]
> Conversion between datasets might not be needed, as joints will be handled as addtional_tfs are, so no need for a new dataset for that.

What do you mean by this? I think you mean to put an if \<there is this field in the dataset\>, then do something.
I don't like the solution, because these ifs will be scattered over the many files in ATOM.

I think its best to do something like. If you do not have an updated config.yml and a dataset of the current version, abort and tell the person the dataset must be updated.

This centralizes in a single conversion script the effort of updating the dataset, rather than scattering all over atom mechanisms to tackle the different versions of the datasets.

Do you agree?

**Comment by manuelgitgomes** [comment]
> I think its best to do something like. If you do not have an updated config.yml and a dataset of the current version, abort and tell the person the dataset must be updated.

Then I think we should make `additional_tfs` mandatory on the dataset as well, and create the dataset 2.x to 3.0 conversion.

I would think it could be interesting to add config versions.
From this we would have a config 1.0 to 2.0 conversion, and state that the `joints` and `additional_tfs` and `package_name` are required.
This would solve  #589, making everything required.
What do you think?

**Comment by miguelriemoliveira** [comment]
I agree, but these are a lot of changes. We should try to minimize changes. 
On the other hand, we are asking everyone to change their config.yml and datasets, so might as well implement everything now.

About the conversion script, I created separate scripts to add the joints, and the package name, but I now see it would be better to have a single update_config_2_to_3. I will work on it (#723 ).

**Comment by miguelriemoliveira** [comment]
This is "old" since we've done so much since. I will close it because I think everything is covered.
