### ISSUE TITLE
Adding a new pattern- ArucoBoard

### ISSUE THREAD

**Issue by Ruthrash** [lardemua/atom#856]
Hey! we have  an aruco board pattern already printed out in our lab and we are trying to use atom to calibrated our multimodal sensor system in our robot. I am a bit unsure where all do I have to incorporate changes for this new pattern as I see this being affected in many scripts like test_rgb_labeller, patterns.py, rgb_labeler, data_collector etc as far as I know. Could you please advise what would be the best approach to add this feature? 

One main discrepancy I am facing is that unlike chessboard and charuco patterns, opencv doesn't assign ids to the corners for aruco but ids for the each tag. and each tag has 4 corners.

**Comment by miguelriemoliveira** [comment]
Hi @Ruthrash ,

thanks for the interest in ATOM. We currently only support charuco or checkerboards.
I have never used and aruco board, but I think its not compatible with a charuco.

We can add this functionality but it will take a while to work on since its not a priority. 
There are several files to chance.

My advise is that you purchase or build a charuco pattern. That would be the fastest way.

**Comment by Ruthrash** [comment]
Thanks Miguel! Since we just purchased a new arucoboard pattern, we didn't opt buying a new charuco pattern. However, I was able to add the arucoboard pattern to ATOM codebase. I am testing it right now with our mutli-modal robot system. I can submit a PR after I'm done testing if you think it'd add value to your codebase. Closing this issue now.

**Comment by miguelriemoliveira** [comment]
> Thanks Miguel! Since we just purchased a new arucoboard pattern, we didn't opt buying a new charuco pattern. However, I was able to add the arucoboard pattern to ATOM codebase. I am testing it right now with our mutli-modal robot system. I can submit a PR after I'm done testing if you think it'd add value to your codebase. Closing this issue now.

That would be great. Thanks!
